services:
  dev-container:
    # TODO: 等服务器到货后搭建一个校园网内的docker镜像源不使用dockerhub
    container_name: devcontainer_${USERNAME}
    environment:
      - USER=${USERNAME}
    image: nanmu111/ldc1614-test-dev-container:latest
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile
    #   args:
    #     # 注意替换为自己的代理地址，使用http/https代理
    #     proxy: "http://127.0.0.1:7890"
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspaces:cached
      - ~/.gitconfig:/home/vscode/.gitconfig # 挂载本地 git 配置
      - ~/.ssh:/home/vscode/.ssh # 挂载本地 SSH 密钥
    command: sleep infinity
    # platforms:
    #   - linux/arm64
    networks:
      - devnet
  # redis-stack:
  #   container_name: redis-stack
  #   # platforms:
  #   #   - linux/arm64
  #   ports:
  #     - 6379:6379
  #     - 8001:8001
  #   environment:
  #     - REDIS_ARGS=--requirepass mypassword
  #   image: redis/redis-stack:latest
  #   networks:
  #     - devnet
  #   volumes:
  #     - redis_data:/data # 持久化存储数据

networks:
  devnet:
    driver: bridge

volumes:
  redis_data:
    driver: local
